version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
    volumes:
      - coolify_web_data:/app/.next
      - coolify_public_data:/app/public
    command: node .next/standalone/server.js
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s


volumes:
  coolify_web_data:
    driver: local
  coolify_public_data:
    driver: local
